export * from './personal-data-repository.abstract';
export * from './user-repository-abstract';
export * from './data-services-abstraction';
export * from './author-repository.abstract';
export * from './book-repository.abstract';
export * from './language-repository.abstract'
export * from './publisher-repository.abstract';
export * from './category-repository.abstract';
export * from './user-situation.abstract'
export * from './book-images-repository.abstract'